#!/usr/bin/bash

I100="󰁹"
I90=""
I50="󰁾"
I20="󰁻"
ICHR=""

percentage=$(upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep 'percentage' | awk -F: '{print int($2)}')
state=$(upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep 'state' | awk -F: '{ gsub(/ /, ""); print $2 }')

if [ "$state" = 'discharging' ]; then
    if [ $percentage -eq 100 ]; then
        echo "$I100 $percentage%"
        echo "$I100 $percentage%"
        echo "#FFFFFF"
    elif [[ $percentage -gt 50 && $percentage -lt 100 ]]; then
        echo "$I90 $percentage%"
        echo "$I90 $percentage%"
        echo "#FFFFFF"
    elif [[ $percentage -gt 20 && $percentage -le 50 ]]; then
        echo "$I50 $percentage%"
        echo "$I50 $percentage%"
        echo "#FFF000"
    else
        echo "$I20 $percentage%"
        echo "$I20 $percentage%"
        echo "#FF0000"
    fi
else
    echo "$ICHR $percentage%"
    echo "$ICHR $percentage%"
    echo "#FFFFFF"
fi
