# taps
tap "homebrew/bundle"
tap "nikitabobko/tap"

# brews
brew "stow"

# casks
cask "aerospace"
cask "brave-browser"
cask "dbeaver-community"
cask "firefox"
cask "hiddenbar"
cask "kitty"
cask "raycast"
cask "scroll-reverser"
cask "signal"
cask "slack"
cask "zed"
